# Generated by Django 2.0.7 on 2018-07-06 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('note_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SitePinger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Unknown', max_length=20)),
                ('system_uptime', models.DurationField(default=datetime.timedelta)),
                ('network_uptime', models.DurationField(default=datetime.timedelta)),
                ('down_sync', models.CharField(default='Not Available', max_length=20)),
                ('up_sync', models.CharField(default='Not Available', max_length=20)),
                ('req_time', models.DurationField(default=datetime.timedelta)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('online', models.BooleanField()),
                ('note', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Note')),
            ],
        ),
    ]
